"""
This file is used to download the images from .har files generated by internet explorer when searching
for images in google images
"""
# Libraries
import datetime
import re
import urllib.request as ur
from os import listdir
from os.path import isfile, join

# image URL ending
image_URL="/images?"

# Images Path location
images_save_path = "D:\\images_to_save_location"

# har folder Path location
har_file_Path = "D:\\har_files_location"

# list of har files in the har_file_Path folder
harfiles = [f for f in listdir(har_file_Path) if isfile(join(har_file_Path, f))]

# regex query to search for images URLS
pat = '((http|https)((?!(http|https)).)*?.(jpeg|jpg|png))'

def download_images(harfile, folderindex):
    """ This Function Takes the name of an .har file and the index of the folder in which
    the image will be saved. It uses regex to get all the URLs of the images and download them"""
    with open(har_file_Path + "\\" + harfile, 'r', encoding="utf8") as myfile:
        data = myfile.read()
        urls = [x.group() for x in re.finditer(pat,data)]

    index = 0
    for url in urls:
        print(url)
        try:
            url = url.replace("\"", "").replace(",", "")
            datenow: datetime = datetime.datetime.now()
            image_name = images_save_path + "\\" + str(folderindex) + "_" + datenow.strftime(
                '%Y%m%d%H%M%S%f') + "_" + str(index) + ".png"
            ur.urlretrieve(url, image_name)
        except:
            a = 0
        index += 1


# loop through all har files and download them
folder_Index = 1
for harfile in harfiles:
    download_images(harfile, folder_Index)
    print(folder_Index)
    folder_Index += 1
